<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../css/index.css" type="text/css"/>
    <title>Maggle</title>
</head>
<body>
    <div class="landing_title">
        <h1>Maggle</h1>
        <div class="landing_sub_title">
            <p>Partagez et restez en contact avec étudiants et alumnis!</p>
        </div>
    </div>
        <div class="sign_up">
            <div class="mail">
                <p> Mail Hetic</p>
            </div>
            <div class="mdp">
                <p>Mot de passe</p>
            </div>
            <div class="mdp_comfirm">
                <p>Confirmation du mot de passe</p>
            </div>
            <div class="create_account">
                <a href="">Créer un compte</a>
        </div>
            <div class="sign_in">
               <a href="">Vous êtes déjà inscrit? Connectez-vous!</a>
            </div>
        </div>
</body>
</html>